# Generated by Django 4.2.6 on 2023-10-31 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_author_user_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='img',
            new_name='image',
        ),
    ]
