# Generated by Django 4.2.6 on 2023-10-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_admin_user_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
