# Generated by Django 4.2.6 on 2023-10-31 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kafe', '0003_alter_product_category'),
        ('afitsan', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakas',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kafe.product'),
        ),
        migrations.AlterField(
            model_name='zakas',
            name='stol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kafe.stol'),
        ),
    ]
