# Generated by Django 4.2.6 on 2023-11-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afitsan', '0003_alter_zakas_product_alter_zakas_stol'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakas',
            name='buyurtma',
            field=models.BooleanField(default=False),
        ),
    ]
