# Generated by Django 4.2.6 on 2023-10-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafe', '0003_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Malumot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=50)),
                ('parol', models.CharField(max_length=50)),
            ],
        ),
    ]
