# Generated by Django 4.2.6 on 2023-10-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafe', '0005_malumot_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='malumot',
            name='idd',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
