# Generated by Django 4.2.6 on 2023-10-31 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kafe', '0006_malumot_idd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='malumot',
            name='idd',
        ),
    ]
