# Generated by Django 4.2.6 on 2023-10-31 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kafe', '0007_remove_malumot_idd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Malumot',
        ),
    ]
