# Generated by Django 5.1.1 on 2024-10-07 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kafe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('date_creat', models.DateField(auto_now_add=True)),
                ('date_edit', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('deliver', models.BooleanField(default=False)),
                ('summa_all', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kafe.product')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kafe.table')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
